name: smartspend_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.8.0
  auto_route: ^7.8.4
  flutter_svg: ^2.0.9
  in_app_review: ^2.0.8
  overlay_support: ^2.1.0
  firebase_messaging: ^14.2.2
  firebase_core: ^2.21.0
  firebase_remote_config: ^4.3.3
  flutter_local_notifications: ^9.8.0+1
  flutter_bloc: ^8.1.3
  share_plus: ^7.2.2
  get_it: ^7.6.4
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  appsflyer_sdk:
  shared_preferences: ^2.2.2
  sliding_up_panel: ^2.0.0+1
  chip_list: ^2.4.4+8
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.2

  cupertino_icons: ^1.0.2
  app_tracking_transparency: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/tab-icons/
    - assets/images/settings/
    - assets/images/news/
    - assets/images/balance/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"